version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./eventbooking.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./:/app
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bepguser
      - POSTGRES_PASSWORD=EventB@2020
      - POSTGRES_DB=eventbooking_db
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
